[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ['@openzeppelin/=lib/@openzeppelin/']
optimizer_runs = 800
solc = '0.8.17'
bytecode_hash = 'none'

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
